FROM haxe:4.3.0-buster

RUN apt-get update \
	&& apt-get install -y --no-install-recommends apt-utils \
	&& yes | apt-get install unzip -y \
	&& yes | apt-get install zip -y

RUN yes | apt-get install -y gcc
RUN yes | apt-get install -y g++


# HAXELIB SETUP
RUN mkdir -p /haxelib
RUN haxelib setup /haxelib

RUN yes | haxelib install utest
RUN yes | haxelib install datetime
RUN yes | haxelib install hxcpp
RUN yes | haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git
RUN yes | haxelib --skip-dependencies git anonstruct https://github.com/triture/anonstruct.git
RUN yes | haxelib --skip-dependencies git apirock https://github.com/triture/apirock.git
RUN yes | haxelib --skip-dependencies git util-kit https://github.com/triture/util-kit.git
RUN yes | haxelib --skip-dependencies git crapp-kit https://github.com/triture/crapp-kit.git


# INSTALLING NODEJS
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

ENV NODE_PATH=/usr/lib/node_modules
ENV NODE_OPTIONS=--max_old_space_size=4096
RUN npm install -g nodemon@2.0.20

WORKDIR /product

CMD ["sh", "/docker-shared/alive.sh"]
